# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from offboard/information_collection_case.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class information_collection_case(genpy.Message):
  _md5sum = "79acd54d777973b93b9b56ccf8677846"
  _type = "offboard/information_collection_case"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """##信息传输完成的标志位
std_msgs/String collection_flag  
uint8 point_n
##目标点到达的标志位
bool arrive_flag
================================================================================
MSG: std_msgs/String
string data
"""
  __slots__ = ['collection_flag','point_n','arrive_flag']
  _slot_types = ['std_msgs/String','uint8','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       collection_flag,point_n,arrive_flag

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(information_collection_case, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.collection_flag is None:
        self.collection_flag = std_msgs.msg.String()
      if self.point_n is None:
        self.point_n = 0
      if self.arrive_flag is None:
        self.arrive_flag = False
    else:
      self.collection_flag = std_msgs.msg.String()
      self.point_n = 0
      self.arrive_flag = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.collection_flag.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.point_n, _x.arrive_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.collection_flag is None:
        self.collection_flag = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.collection_flag.data = str[start:end].decode('utf-8')
      else:
        self.collection_flag.data = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.point_n, _x.arrive_flag,) = _get_struct_2B().unpack(str[start:end])
      self.arrive_flag = bool(self.arrive_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.collection_flag.data
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B().pack(_x.point_n, _x.arrive_flag))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.collection_flag is None:
        self.collection_flag = std_msgs.msg.String()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.collection_flag.data = str[start:end].decode('utf-8')
      else:
        self.collection_flag.data = str[start:end]
      _x = self
      start = end
      end += 2
      (_x.point_n, _x.arrive_flag,) = _get_struct_2B().unpack(str[start:end])
      self.arrive_flag = bool(self.arrive_flag)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2B = None
def _get_struct_2B():
    global _struct_2B
    if _struct_2B is None:
        _struct_2B = struct.Struct("<2B")
    return _struct_2B
